Fix implementation according to the latest changes
artipie/vertx-server pull request #2
Opened 2020-02-07 17:05 UTC by Sammers21

2020-02-10 15:18 UTC, g4s8 commented
@0crat in

2020-02-10 15:18 UTC, 0crat commented
I'm not managing `artipie/vertx-server` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

2020-02-11 10:25 UTC, g4s8 requested changes
@Sammers21 just one comment

2020-02-11 10:25 UTC, g4s8 commented on pom.xml
> +      <version>1.0-SNAPSHOT</version>
@Sammers21 please don't use snapshot versions, use `0.2` versions instead

2020-02-11 11:16 UTC, g4s8 approved these changes

2020-02-12 08:15 UTC, merged

2020-02-12 09:11 UTC, Sammers21 commented
@rultor, release tag=`0.1`

2020-02-12 09:15 UTC, rultor commented
> @rultor, release tag=`0.1`

@sammers21 OK, I will release it now. Please check the progress [here](https://www.rultor.com/t/21358-585105776)

2020-02-12 09:16 UTC, rultor commented
> @rultor, release tag=`0.1`

@sammers21 Oops, I failed. You can see the full log [here](https://www.rultor.com/t/21358-585105776) (spent 13s)

```
+ set -e
+ set -o pipefail
++ dirname ./run.sh
+ cd .
+ echo 25978
+ echo '1.68.9 b65c1294d'
1.68.9 b65c1294d
+ date
Wed Feb 12 10:16:04 CET 2020
+ uptime
 10:16:04 up 118 days,  7:24,  0 users,  load average: 5.31, 5.73, 5.53
+ cat
.rultor.yml in yegor256/home doesn't allow artipie/vertx-server to use its assets (there are 134 friends), see http://doc.rultor.com/reference.html#assets
+ exit -1
'cid' file is absent, container wasn't started correctly
```

2020-02-12 10:58 UTC, Sammers21 commented
@rultor, release tag=`0.1`

2020-02-12 10:58 UTC, rultor commented
> @rultor, release tag=`0.1`

@sammers21 Thanks for your request. @g4s8 Please confirm this.

2020-02-12 11:00 UTC, g4s8 commented
@rultor release, tag=`0.1`

2020-02-12 11:00 UTC, rultor commented
> @rultor release, tag=`0.1`

@g4s8 OK, I will release it now. Please check the progress [here](https://www.rultor.com/t/21358-585151414)

2020-02-12 11:03 UTC, rultor commented
> @rultor release, tag=`0.1`

@sammers21 @g4s8 Oops, I failed. You can see the full log [here](https://www.rultor.com/t/21358-585151414) (spent 2min)

```
+ docker ps --filter=status=exited
+ grep --quiet '\sartipie_vertx-server_2\s*$'
+ ls -al .
total 720
drwx------  3 rultor rultor   4096 Feb 12 12:01 .
drwxrwxrwt 12 root   root   684032 Feb 12 12:01 ..
-rwxrwxr-x  1 rultor rultor    338 Feb 12 12:01 entry.sh
-rw-rw-r--  1 rultor rultor      6 Feb 12 12:01 pid
-rw-rw-r--  1 rultor rultor   1192 Feb 12 12:01 pubring.gpg
drwxrwxr-x  5 rultor rultor   4096 Feb 12 12:01 repo
-rwxrwxr-x  1 rultor rultor   6263 Feb 12 12:01 run.sh
-rw-rw-r--  1 rultor rultor    764 Feb 12 12:01 script.sh
-rw-rw-r--  1 rultor rultor   2570 Feb 12 12:01 secring.gpg
-rw-rw-r--  1 rultor rultor    391 Feb 12 12:01 settings.xml
-rw-rw-r--  1 rultor rultor   4590 Feb 12 12:01 stdout
++ pwd
++ pwd
+ docker run -t --rm -v /tmp/rultor-GnIK:/main --env=JAVA_HOME=/usr/lib/jvm/java-11-openjdk --env=head=git@github.com:artipie/vertx-server.git --env=tag=0.1 '--env=scripts=( '\''export '\''\'\'''\''JAVA_HOME=/usr/lib/jvm/java-11-openjdk'\''\'\'''\'''\'' '\'';'\'' '\''export '\''\'\'''\''head=git@github.com:artipie/vertx-server.git'\''\'\'''\'''\'' '\'';'\'' '\''export '\''\'\'''\''tag=0.1'\''\'\'''\'''\'' '\'';'\'' '\''export '\''\'\'''\''head_branch=master'\''\'\'''\'''\'' '\'';'\'' '\''export '\''\'\'''\''author=g4s8'\''\'\'''\'''\'' '\'';'\'' '\''export LC_ALL=en_US.UTF-8'\'' '\'';'\'' '\''export LANG=en_US.UTF-8'\'' '\'';'\'' '\''export LANGUAGE=en_US.UTF-8'\'' '\'';'\'' '\''sudo gem install pdd -v 0.20.5'\'' '\'';'\'' '\''sudo gem install xcop'\'' '\'';'\'' '\''pdd -f /dev/null'\'' '\'';'\'' '\''gpg --import /home/r/pubring.gpg'\'' '\'';'\'' '\''gpg --allow-secret-key-import --no-tty --batch --import /home/r/secring.gpg'\'' '\'';'\'' '\''mvn versions:set "-DnewVersion=${tag}" --settings ../settings.xml'\'' '\'';'\'' '\''git commit -am "${tag}"'\'' '\'';'\'' '\''mvn clean deploy -Partipie,publish,sonatype,qulice,gpg-sign --errors --settings ../settings.xml'\'' '\'';'\'' )' --env=head_branch=master --env=author=g4s8 --hostname=docker --privileged --memory=6g --memory-swap=16g --oom-kill-disable --cidfile=/tmp/rultor-GnIK/cid -w=/main -v /var/run/docker.sock:/var/run/docker.sock --entrypoint=/main/entry.sh --name=artipie_vertx-server_2 g4s8/rultor-jdk11:alpine3.10 /main/entry.sh
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
+ set -e
+ set -o pipefail
+ shopt -s dotglob
+ useradd -m -G sudo r
Creating mailbox file: No such file or directory
+ echo '%sudo ALL=(ALL) NOPASSWD:ALL'
+ cp -R /root/.bundle /root/.gem /root/.wget-hsts /root/empty /home/r
+ cp -R ./cid ./end.sh ./entry.sh ./pid ./pubring.gpg ./repo ./run.sh ./script.sh ./secring.gpg ./settings.xml ./stdout /home/r
+ rm -rf repo
+ chown -R r:r /home/r
+ chmod a+x /home/r/script.sh
+ su --login r --command /home/r/script.sh
+ set -e
+ set -o pipefail
+ shopt -s expand_aliases
+ alias 'sudo=sudo -i'
+ export HOME=/home/r
+ HOME=/home/r
+ cd /home/r/repo
+ export JAVA_HOME=/usr/lib/jvm/java-11-openjdk
+ JAVA_HOME=/usr/lib/jvm/java-11-openjdk
+ export head=git@github.com:artipie/vertx-server.git
+ head=git@github.com:artipie/vertx-server.git
+ export tag=0.1
+ tag=0.1
+ export head_branch=master
+ head_branch=master
+ export author=g4s8
+ author=g4s8
+ export LC_ALL=en_US.UTF-8
+ LC_ALL=en_US.UTF-8
+ export LANG=en_US.UTF-8
+ LANG=en_US.UTF-8
+ export LANGUAGE=en_US.UTF-8
+ LANGUAGE=en_US.UTF-8
+ sudo -i gem install pdd -v 0.20.5
Successfully installed pdd-0.20.5
ERROR:  While executing gem ... (Gem::DocumentError)
    RDoc is not installed: cannot load such file -- rdoc/rdoc
container f777c65b24f1533ae106d89e55a44a92a191a98dbd643f792c6c8b8f71fc21ef is dead
Wed Feb 12 12:03:37 CET 2020
```