fix: validate README.md
artipie/vertx-server pull request #32
Opened 2022-06-17 13:39 UTC by dgarus

Part of https://github.com/artipie/artipie/issues/1031

- Corrected and extended readme file
- added codecov report

2022-06-17 13:47 UTC, dgarus commented
@olenagerasimova could you review, please?
I don't have permissions for a review request here.

2022-06-17 13:53 UTC, olenagerasimova requested changes
@dgarus thanks, one suggestion

2022-06-17 13:53 UTC, olenagerasimova commented on README.md
>  [![PDD status](http://www.0pdd.com/svg?name=artipie/vertx-server)](http://www.0pdd.com/p?name=artipie/vertx-server)
I'd suggest to add some simple explanation: what is `vertx-server`, what can it do and how we use it in artipie (IT for adapters and as http server in artipie/artipie)

2022-06-20 10:14 UTC, dgarus commented
@olenagerasimova 
added a sentence what `vertx-server` is, could you please have a look?

2022-06-20 10:59 UTC, olenagerasimova approved these changes
@dgarus thanks, merging

2022-06-20 10:59 UTC, merged